#! /usr/bin/env python

import rospy
from control_listener.motor_controller import MotorController

if __name__ == '__main__':
    try:
        controller = MotorController()
        # Started Oscillating at P=10. So set to 5
        controller.init(0, 5, 3, 0.8)
    except rospy.ROSInterruptException:
        pass
