#! /usr/bin/env python

import rospy
from control_listener.motor_controller import MotorController

if __name__ == '__main__':
    try:
        controller = MotorController()
        controller.init(0, 1, 0, 0)
    except rospy.ROSInterruptException:
        pass