#! /usr/bin/env python

from control_listener.cameraMountController import cameraMountController

if __name__ == '__main__':
    try:
        node = cameraMountController()
        node.init(50, 4, 2, 0.1)
    except KeyboardInterrupt:
        node.turnOff()
