#! /usr/bin/env python

from control_listener.cameraMountController import cameraMountController

if __name__ == '__main__':
    try:
        node = cameraMountController()
        node.init()
    except KeyboardInterrupt:
        node.turnOff()